export type {
    Primitive,
    TypedArray,
    TypedArrayConstructor,
    NumericTypedArray,
    NumericTypedArrayConstructor,
    Builtin,
    BuiltinObject,
    DeepReadonly,
    DeepMutable,
    JsonPrimitive,
    JsonObject,
    JsonArray,
    JsonValue,
    Brand,
    Nominal,
    Opaque,
    MaybePromise,
    Constructor,
    AbstractConstructor,
    ArrayElement,
    NonEmptyReadonlyArray,
    Mutable,
    ReadonlyTuple2,
    ReadonlyTuple3,
    ReadonlyTuple4,
} from './types';

export type {
    CompareResult,
    Comparable,
    OrderKey,
    Comparer,
    EqualityComparer,
    Equatable,
    KeySelector,
    PropertyPath,
    ExtractPropertyType,
    ComparerOptions,
    EqualityComparerOptions,
    DeepPartial,
    KeysOfType,
} from './comparer/comparer';

export {
    DefaultComparer,
    DefaultEqualityComparer,
    ReverseComparer,
    CompositeComparer,
    KeyComparer,
    StringComparer,
    NumberComparer,
    DateComparer,
    DeepEqualityComparer,
    ComparerError,
    InvalidOperationError,
    comparer,
    equality,
    createOrderKey,
    createPropertyAccessor,
    sorted,
    min,
    max,
    isEquatable,
    isComparer,
    isEqualityComparer,
} from './comparer/comparer';

export type { ICloneable } from './clone/cloner';
export { cloneData, deepClone } from './clone/deep-clone';
export type { Disposable, IDisposable } from './disposable';
export { deepFreeze } from './freeze';

export type {
    SingletonKey,
    SingletonState,
    SingletonLifecycle,
    ISingleton,
    IAsyncSingleton,
    IScopedSingleton,
    ISingletonScope,
    ISingletonRegistry,
    ISingletonMetadata,
    IAsyncSingletonMetadata,
    IScopedSingletonMetadata,
    SingletonOptions,
    AsyncSingletonOptions,
    SingletonDisposer,
    ScopeDisposer,
    ExtractSingletonType,
} from './singleton';

export {
    SingletonImpl,
    AsyncSingletonImpl,
    ScopedSingletonImpl,
    SingletonScopeImpl,
    SingletonRegistryImpl,
    SingletonError,
    SingletonErrorCode,
    createRootScope,
    getGlobalRegistry,
    resetGlobalRegistry,
    resetGlobalRegistryAsync,
    create as createSingleton,
    createAsync as createAsyncSingleton,
    createScoped as createScopedSingleton,
    createLazy as createLazySingleton,
    createLazyAsync as createLazyAsyncSingleton,
    fromValue as singletonFromValue,
    fromPromise as singletonFromPromise,
    createRegistered as createRegisteredSingleton,
    createRegisteredAsync as createRegisteredAsyncSingleton,
    isSingleton,
    isAsyncSingleton,
    isScopedSingleton,
    isAnySingleton,
    resolve as resolveSingleton,
    tryResolve as tryResolveSingleton,
    map as mapSingleton,
    mapAsync as mapAsyncSingleton,
    combine as combineSingletons,
    combineAsync as combineAsyncSingletons,
} from './singleton';
