export type { IColorLike, IVec2Like } from '@axrone/numeric';
export type {
    CircleShape,
    CircleShapeInput,
    EllipseShape,
    EllipseShapeInput,
    GradientColorSpace,
    GradientSpread,
    GradientStop,
    GradientStopInput,
    GradientUnits,
    LineShape,
    LineShapeInput,
    LinearGradientPaint,
    LinearGradientPaintInput,
    RadialGradientPaint,
    RadialGradientPaintInput,
    RectangleShape,
    RectangleShapeInput,
    Shape2D,
    ShapeAppearance,
    ShapeAppearanceInput,
    ShapeApproximationOptions,
    ShapeBounds,
    ShapeColorInput,
    ShapeId,
    ShapeKind,
    ShapePaint,
    ShapePaintInput,
    ShapePointInput,
    ShapeStroke,
    ShapeStrokeAlignment,
    ShapeStrokeInput,
    TriangleShape,
    TriangleShapeInput,
} from './types';
export {
    PaintValidationError,
    SHAPES_2D_ERROR_CODE,
    Shapes2DError,
    ShapeValidationError,
} from './errors';
export {
    createColor,
    createGradientStop,
    createLinearGradientPaint,
    createPaint,
    createRadialGradientPaint,
    createSolidPaint,
    createStroke,
    isLinearGradientPaint,
    isRadialGradientPaint,
    isShapePaint,
    isSolidPaint,
} from './paint';
export {
    createCircleShape,
    createEllipseShape,
    createLineShape,
    createRectangleShape,
    createTriangleShape,
    isCircleShape,
    isEllipseShape,
    isLineShape,
    isRectangleShape,
    isShape2D,
    isTriangleShape,
    matchShape,
} from './shape';
