export type { IColorLike, IVec2Like } from '@axrone/numeric';
export type {
    CircleShape,
    CircleShapeInput,
    CompiledShape2D,
    EllipseShape,
    EllipseShapeInput,
    GradientColorSpace,
    GradientSpread,
    GradientStop,
    GradientStopInput,
    GradientUnits,
    LineShape,
    LineShapeInput,
    LinearGradientPaint,
    LinearGradientPaintInput,
    RadialGradientPaint,
    RadialGradientPaintInput,
    RectangleShape,
    RectangleShapeInput,
    Shape2D,
    ShapeAppearance,
    ShapeAppearanceInput,
    ShapeApproximationOptions,
    ShapeBounds,
    ShapeCompileOptions,
    ShapeColorInput,
    ShapeId,
    ShapeKind,
    ShapeFingerprint,
    ShapeHitTarget,
    ShapePaint,
    ShapePaintInput,
    ShapePointInput,
    ShapeMesh2D,
    ShapeRegistryOptions,
    ShapeRegistryStats,
    ShapeStroke,
    ShapeStrokeAlignment,
    ShapeStrokeInput,
    TriangleShape,
    TriangleShapeInput,
} from './types';
export {
    PaintValidationError,
    SHAPES_2D_ERROR_CODE,
    SerializationError,
    ShapeRegistryError,
    Shapes2DError,
    ShapeValidationError,
} from './errors';
export {
    createColor,
    createGradientStop,
    createLinearGradientPaint,
    createPaint,
    createRadialGradientPaint,
    createSolidPaint,
    createStroke,
    isLinearGradientPaint,
    isRadialGradientPaint,
    isGradientPaint,
    isShapePaint,
    isSolidPaint,
    createGradientLookupTable,
    createPaintFingerprint,
    modulatePaintAlpha,
    samplePaint,
} from './paint';
export {
    createCircleShape,
    createEllipseShape,
    createLineShape,
    createRectangleShape,
    createTriangleShape,
    isCircleShape,
    isEllipseShape,
    isLineShape,
    isRectangleShape,
    isShape2D,
    isTriangleShape,
    matchShape,
} from './shape';
export {
    buildFillMesh,
    buildStrokeMesh,
    compileShape,
} from './mesh';
export {
    containsPoint,
    getShapeArea,
    getShapeBounds,
    getShapeCentroid,
    getShapePerimeter,
    hitTestShape,
    sampleShapePaint,
} from './queries';
export type {
    SerializedCircleShape,
    SerializedEllipseShape,
    SerializedLineShape,
    SerializedLinearGradientPaint,
    SerializedPaint,
    SerializedRadialGradientPaint,
    SerializedRectangleShape,
    SerializedShape,
    SerializedSolidPaint,
    SerializedStroke,
    SerializedTriangleShape,
} from './serialization';
export {
    createShapeFingerprint,
    deserializePaint,
    deserializeShape,
    deserializeStroke,
    serializePaint,
    serializeShape,
    serializeStroke,
    stringifyPaint,
    stringifyShape,
} from './serialization';
export { ShapeRegistry } from './registry';
